language: node_js
node_js:
- node
env:
  global:
  - DISPLAY=:99.0
services:
- xvfb
addons:
  firefox: latest
script:
- npm run lint
- npm test
- npm run docs
deploy:
  - provider: pages
    local_dir: docs
    skip_cleanup: true
    github_token:
      secure: "rmlMFLAmFNv+MMnKx3qPZBrQ/KUARNwAvhR2OJl4LZw/L1jWIEWM+9dTmMzKybOlIQrLEkS4T/maPqoXgAuG9bJCSXEvGjJtbJau0+5wUKDAEnOlUa5zAZsBoMxRKuakH7a9kKhtzWJ3DzCnlqbEDQQhqRRzioVAaS4gk6/Ayjo9GXdBBQWu08wZxHh4+KGshkpxmTyuFS9HL3B3jLq+xQi2McLT6UbRRMo4eZpgYA/7ohvQ/nmjIa8rqUIj5nXrz27ReiTrEMlikSXsI1RwTAjXOdLRNjLvpinGbpBfRG3nUjYMKiM5nLaGiCi53yZQF2P2vmDqQu+JPJIaNDLJ8GELpJ8HzIz5hy4YLtOWMfm+35dX+duCct90Q2bCl9P/fCMhLnM2EvyyuXD3ug9xWmJTDr6VU8MZetCOoPz7XsiC7z6DPbw34c3RSAbrjnyupz4xt1YReQDtdgbb8cGKGiPnU7EIIdh9Hop8IXAH6nq7uf71/u1ctXrXLOgKDI0hbM66aQt3WrtkGAabkZnCNza5lmuqHlnzrJQpcKX+j+thzPz5d6pAt8QqdYgVfDFTd+kOxX1lQ8k0wKx830FtHqgE5IpX3Czz9x7Xeq25gd8B5UQ3WMEFjGew3H81hWGuc2Fxr4lfI7iQSaiRI7XZjPOjDxL+q5L5sPsn5MRnUoc="
    on:
      tags: true
      repo: mrichar1/jsonapi-vuex
  - provider: npm
    email: m.richardson@ed.ac.uk
    api_key:
      secure: vYv6EqcfqTrjQrePGE8N2yh8hzV0Pqmb2FtP4svxVlMd/l8LwlrllSvjlLGS5yPgTk9xdG+79CVKv0JbKNO9q4RojAm182fkeTb5NlfRtHlnI2hpgQk65Xqk3MrKieSRgW5YZ4DToqfJuW5sS1f/d5tk1rYmfM6QrcktrOWXamtLzyJLj8EdbPtA+8ha+t77P/JmWxvTgF5XlwRYDHhH4W6OpPvmPSY7Qgv0H2toFZdS/20KrQCPDJgAnW5Alu0yCBfjT4WVdFyTLb3x2vkjOtkpYvOfLxeDSguwQMM4rRh+7C6dRGOjyxiwDlN12X9su4rWwHId0Tovq/GCWs/u41CS6QdMIrv10ZHE4x/BTgAb3kyyVMe8CXLIOC5eU/zo2jBmYgMxUG+g+h1Rjc5JI5aXNKfY67DNcNxJc3aK7qFO1GbOT2s+k8GrkmgDczORg8TCtpXd3+0key5o4uYqEmeu7EAb4vDBu1Qgjj+O3i3AiV7ysb4WyM6oDTWLkyq3WCFG01gopoBqkzH+B5yVQHuEYr6aYefNv9mdVLyONJuPZkoRII0R2p602R6OE5XJZALQHiR2Rkb9xMydbw/wrSBTgjkLuZWT6kMOhrbDtX0dP0cWTSl2u3pEFG3uIX+avgjqjQJvcd/p4v6Ay6oRtc2TOJUAou+G7UzUjc4ouno=
    on:
      tags: true
      repo: mrichar1/jsonapi-vuex
