language: node_js
node_js:
- node
env:
  global:
  - DISPLAY=:99.0
services:
- xvfb
addons:
  firefox: latest
script:
- npm run lint
- npm test
deploy:
  provider: npm
  email: m.richardson@ed.ac.uk
  api_key:
    secure: vYv6EqcfqTrjQrePGE8N2yh8hzV0Pqmb2FtP4svxVlMd/l8LwlrllSvjlLGS5yPgTk9xdG+79CVKv0JbKNO9q4RojAm182fkeTb5NlfRtHlnI2hpgQk65Xqk3MrKieSRgW5YZ4DToqfJuW5sS1f/d5tk1rYmfM6QrcktrOWXamtLzyJLj8EdbPtA+8ha+t77P/JmWxvTgF5XlwRYDHhH4W6OpPvmPSY7Qgv0H2toFZdS/20KrQCPDJgAnW5Alu0yCBfjT4WVdFyTLb3x2vkjOtkpYvOfLxeDSguwQMM4rRh+7C6dRGOjyxiwDlN12X9su4rWwHId0Tovq/GCWs/u41CS6QdMIrv10ZHE4x/BTgAb3kyyVMe8CXLIOC5eU/zo2jBmYgMxUG+g+h1Rjc5JI5aXNKfY67DNcNxJc3aK7qFO1GbOT2s+k8GrkmgDczORg8TCtpXd3+0key5o4uYqEmeu7EAb4vDBu1Qgjj+O3i3AiV7ysb4WyM6oDTWLkyq3WCFG01gopoBqkzH+B5yVQHuEYr6aYefNv9mdVLyONJuPZkoRII0R2p602R6OE5XJZALQHiR2Rkb9xMydbw/wrSBTgjkLuZWT6kMOhrbDtX0dP0cWTSl2u3pEFG3uIX+avgjqjQJvcd/p4v6Ay6oRtc2TOJUAou+G7UzUjc4ouno=
  on:
    tags: true
    repo: mrichar1/jsonapi-vuex
